server:
  port: 8081
feign:
  hystrix:
    enabled=true:
SERVICE1:
  # 服务实例列表
  listOfServers: http://localhost:8086,http://localhost:8087
  # 这个负载均衡器不做重试
  MaxAutoRetriesNextServer: 0
  MaxAutoRetries: 0
  ribbon:
    # 负载策略
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule
    # 设置它的服务实例信息来自配置文件, 如果不设置NIWSServerListClassName就会去euereka里面找
    NIWSServerListClassName: com.netflix.loadbalancer.ConfigurationBasedServerList

person:
  name: zhangct
  age: 41
  likes:
    - games
    - fitness
    - study